Repository sendsmaily/smaily-woocommerce-plugin, pull requests merged in 2020-12, with the labels that each got.

#72 Smaily plugin settings "General" tab refinement
  templates/smaily-woocommerce-admin.php
Labels: enhancement

#74 Wordpress 5.6 compatibility tested
  CHANGELOG.md
  readme.txt
Labels: maintenance

#75 Improve plugin description to better describe the plugin's features
  CHANGELOG.md
  README.md
  readme.txt
Labels: documentation, maintenance

#78 WP version not 4.5 in readme
  README.md
  readme.txt
Labels: documentation, maintenance

#77 Dequeue 3rd party styles in module settings page
  inc/Base/Enqueue.php
Labels: bug
