Repository sendsmaily/smaily-woocommerce-plugin, pull requests merged in 2020-11, with the labels that each got.

#63 Escaped '&' character caused base64 auth to fail
  inc/Base/DataHandler.php
  templates/smaily-woocommerce-admin.php
Labels: bug

#66 1.6.1 release
  CHANGELOG.md
  README.md
  assets/screenshot-6.png
  inc/Base/DataHandler.php
  inc/Widget/SmailyWidget.php
  lang/smaily-et.mo
  lang/smaily-et.po
  lang/smaily-et_EE.mo
  lang/smaily-et_EE.po
  lang/smaily.pot
  readme.txt
  smaily-for-woocommerce.php
  templates/smaily-woocommerce-admin.php
Labels: release

#68 Add first iteration of contribution guide
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, maintenance
