Repository sendsmaily/smaily-woocommerce-plugin, pull requests merged in 2021-07, with the labels that each got.

#105 Add a section about migrations to CONTRIBUTION guide
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, maintenance

#106 Update CONTRIBUTION guide table of contents
  CONTRIBUTING.md
Labels: documentation, maintenance

#107 Improve widget responsive design
  inc/Widget/SmailyWidget.php
  static/admin-widget-style.css
Labels: bug

#110 Release 1.8.1 checklist changes
  CHANGELOG.md
  assets/screenshot-7.png
  readme.txt
  smaily-for-woocommerce.php
Labels: documentation, maintenance

#109 Release 1.8.1
  CHANGELOG.md
  assets/screenshot-7.png
  inc/Widget/SmailyWidget.php
  readme.txt
  smaily-for-woocommerce.php
  static/admin-widget-style.css
Labels: release

#112 WordPress 5.8 compatibility tested
  Dockerfile
  inc/Widget/SmailyWidget.php
  readme.txt
  static/admin-widget-style.css
Labels: maintenance

#114 Release 1.9.0 checklist changes.
  CHANGELOG.md
  assets/screenshot-7.png
  assets/screenshot-8.png
  assets/screenshot-9.png
  lang/smaily-et.mo
  lang/smaily-et.po
  lang/smaily-et_EE.mo
  lang/smaily-et_EE.po
  lang/smaily.pot
  readme.txt
  smaily-for-woocommerce.php
Labels: documentation, maintenance

#113 Release 1.9.0
  CHANGELOG.md
  Dockerfile
  assets/screenshot-7.png
  assets/screenshot-8.png
  assets/screenshot-9.png
  inc/Widget/SmailyWidget.php
  lang/smaily-et.mo
  lang/smaily-et.po
  lang/smaily-et_EE.mo
  lang/smaily-et_EE.po
  lang/smaily.pot
  readme.txt
  smaily-for-woocommerce.php
  static/admin-widget-style.css
Labels: release
