Repository sendsmaily/smaily-woocommerce-plugin, pull requests merged in 2021-05, with the labels that each got.

#93 Setup and configure development tooling
  .github/workflows/release.yaml
  .gitignore
  .vscode/settings.json
  CONTRIBUTING.md
  composer.json
  composer.lock
  phpcs.xml
  release.sh
  vendor/autoload.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_namespaces.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
Labels: maintenance

#96 Release 1.7.2 checklist changes
  CHANGELOG.md
  readme.txt
  smaily-for-woocommerce.php
Labels: documentation, maintenance

#92 Subscription form widget refinement
  .github/workflows/release.yaml
  .gitignore
  .vscode/settings.json
  CONTRIBUTING.md
  composer.json
  composer.lock
  inc/Base/Enqueue.php
  inc/Widget/SmailyWidget.php
  phpcs.xml
  release.sh
  static/admin-widget-style.css
  static/admin-widget.js
  static/jscolor.min.js
  static/layouts/email-layout1.svg
  static/layouts/email-layout2.svg
  static/layouts/email-layout3.svg
  static/layouts/email-layout4.svg
  static/layouts/email-layout5.svg
  vendor/autoload.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_namespaces.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
Labels: enhancement
